default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: hostn_ride_development
  username: hostn_ride
  password: hostn_ride_password
  host: pg_hostn_ride
  port: 5432

test:
  <<: *default
  database: hostn_ride_test
  username: hostn_ride
  password: hostn_ride_password
  host: pg_hostn_ride
  port: 5432

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
